language: node_js
node_js:
- lts/*
before_script:
- npm run build
- node make.js build
before_deploy:
- node make.js after_build
deploy:
  provider: npm
  email: at@cimpress.com
  api_key:
    secure: T0bOp9D+JXI60zthNS/1qwJMP35b2aySmDpN6HLNB5qT3JiCcwe/8zeiTUvSSua70z1fSoykOy5C1jTWf9Zds989DSaO6IsGWrrtDT4456HrLT/kZuTDOuUc1sXDUfuUBdv2QI6PezyCXYy29nN5ocfMG0ogkza3KE9vKUKC7ikGct72A3Li8qmwzfqR073/6y9QenhQZ+lIhdsBWxzGDiRs0BArfKmd0BtaDQSR+b6UCs/xeVj8rz+A4LIA/3Jjc+ZqhoczkpO+qbggV3jgtTyWkL9zJMHR5QuAZmQzMPTmXpLdK5JvuL4pBi3SqzH4YVnmc3wO4Iz2D45KhA1KT65kx09pDRwuJnSLMZ6H+TqzKkarz7Ro7KMg9n7HVYaocYOeJuc/Rd9KFRpXJX10D9ot/ruMG4KAmxV4k3/BHNCXgT6mNMr3PQVc1AOylt1Fg3Ua7hPQ3JJ2+im3eDCQQhyophQdTCAzk4rXBF0WUvVIcXM8BqzztDFtcQukcB179U83qsR0jsDFDTsk2N8ZH8UZXiW+xHt8ncskAbpmbpFsUj+Ocny7ZaCg0/qf443KqqwQ8lgfCsO9DFpsi2q+gSxifrs9YsUNZCWVJG0oMQTnfvbXQ0hQI1+hhrkQX11fXdD4nFY0LUvgpRaYrUJaGm2UoUl/iQMI0RX490GzWLc=
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != master"
branches:
  only:
  - master
  - "/^release.*/"
env:
  global:
    secure: Uy3Ef9lzxtVGdKIh4jRPqjTIXDY9s9wXVvEtwtJRtQGor26TjeqfEN5Sr8fj0Vk+KrmdiycSALbfg5JIum5whP9LxnWWR2LKyfcjU8W/LmfdQ6lGxBXe/Kjrqkgo/G+WmKIFjqCSuuFOvSdB15mDqBmklsdC87pKOq41FYNj65+YX+KgNdiYmEE/WgVe4Qxvo6LwX6ki23uQQE5gaB8iidVZuOuHKXH9pYCsFovTSUeTOcn4IIGGkywprh6FvIc/+/P4J7x2/Jy1lRkXMRMmyVi9OoKStxCnD88wsRdUveJnLO6dyXFVSUCWI0WmbchFvDX9MmAidCxMbhO7qcQTzNraes/yDmMM6bWtIU0SLKrzTh60XpAHZDZfXc2ZbhMWlRyMu7B3f3lEf9VivPUPtNOnDcOwYGN+10Z96KQsB/4R7IkePxp81EnzTcORZZv9zwHRRVO7aatc1th89bgZJUPi6WDo7rOKa+X+iFKmsqWw5Hndb/PM49aMu59DBQ/VYB0jTUHZXLkwq9sLFYMAiT8tilkiAwfvCpV8Jg8/Eu+70QiG8tFrf+VsWRwiMOmThrwx0jkR9SZGxItKK453H6jf3zmDuqanGGb3YM4icu87JGNKRj14uIkbp13RExs8ExrQJ9lhlkM/E3a14cyUprC8ziqjXMTFOhalJ6yXSWg=
